const languageEnglish = {
    message1: {
        Nomessage: 'No message',
        Oracle: 'Oracle',
        Quote: 'Quote',
        Income: 'Income',
        address: 'Token address',
        price: 'Please enter price',
        USDT: 'USDT',
        Staking: 'Staking assets',
        Fee: 'Fee',
        Estimated: 'Estimated mining output',
        balanceETH: 'ETH balance',
        balanceUSDT: 'balance',
        amount: 'Max',
        quqteBtn: 'QUOTE MINING',
        Verifying: 'Verifying Quotation',
        Quoteuser: 'Quote',
        progress: 'verifcation progress',
        TAKER: 'TAKER',
        RETRIEVE: 'RETRIEVE',
        Penalty: 'Penalty for Quotation Deviation',
        Penaltybottom: '10% deviation from the latest quotation price.The current quotation needs to staking at least 100 ETH',
        Penaltybottom2: '10% deviation from the latest quotation price.The current quotation needs to staking at least 300 ETH',
        CONFIRMbtn: 'CONFIRM',
        Penaltybottoms: '10% deviation from the latest quotation price.The current quotation needs to staking 10 times the scale of assets',
        Penaltybottoms2: '10% deviation from the latest quotation price.The current quotation needs to staking 10 times the scale of assets',
        Annualized: 'Annualized return on holding NEST',
        average: '7day average annualization rate of return by holding NEST',
        Cumufative: 'Cumufative mumber of quotations(24H)',
        Incomecontract: 'Income contract address',
        Incomecontract2: ' Token address',
        NEST: ' token addres',
        Depositincome: 'Deposit to ',
        Depositincome2: ' to get income',
        total: ' total circulation',
        SavedNEST: 'Saved ',
        earningspercentage: 'MY earnings percentage',
        balanceNEST: ' balance',
        Approvedamount: 'Approved amount',
        WITHDRAW: 'WITHDRAW',
        DEPOSITE: 'DEPOSIT',
        distribution: 'ETH income distribution stating',
        distribution2: 'ETH income distribution ending',
        totals: 'ETH total income',
        Savings: 'Savings Fund ETH',
        My: 'My earnings ETH',
        CLAIM: 'CLAIM',
        Quotation: 'No Quotation',
        AllOracle: 'AllOracle',
        Favorites: 'Favorites',
        fh_warn: 'No available income',
        day: 'd: ',
        hours: 'h: ',
        sec: 'm',
        connect: 'Connect Wallet',
        pc_warn: 'Penalty for Quotation Deviation!',
        null: 'Quotation cannot be empty',
        crsj: "Cannot deposit during the income collection period",
        sysj: 'Income collection has not started',
        sq: "Approved",
        ysq: 'Unapproved',
        qp_ysq: 'Click to cancel approve',
        qp_wsq: 'Click to approve',
        cd_title: 'Quotation Taker',
        cd_select: 'Choose the direction and amount of the order',
        cd_inputPrice: 'Additional quotation',
        cd_require: 'Taker need to initiate a new quotation, and the staked assets of quotation is twice the size of taker assets'
    },
    message2: {
        Taker: 'ETH/DAI Quotation Taker',
        Choose: 'Choose the direction and amount of the order',
        Quoteprice: 'Quote price',
        In: 'In',
        Pay: 'Pay',
        Fee: 'Fee',
        quotation: 'Additional quotation',
        text: 'Taker need to initiate a new quotation,and the staked assets of quotation is twice the of taker assets',
        ETHbalance: 'ETH balance',
        USDTbalance: 'USDT balance',
        Approvedamount: 'Approved amount',
        USDTApprove: 'USDT Approve',
        CANCEL: 'CANCEL',
        CONFIRM: 'CONFIRM',
        Customize: 'Customize',
        MAX: 'Max',
        n_bz: ' not sufficient funds',
        sq_bz: 'Insufficient approved amount',
        saved_nest: 'Saved ',
    },
    message3: {
        auction: 'Create auction',
        Token: 'Oracle Token address',
        pair: 'Quote pair',
        output: 'Mining output',
        authority: 'Auction authority',
        amount: 'Initial auction amount',
        duration: 'Auction duration',
        NEST: 'NEST balance',
        Approved: 'Approved amount',
        balance: 'DAI balance',
        Oracle: 'ETH/DAI Oracle Auction',
        address: ' address',
        Lasted: 'Lasted bid',
        bid: 'My bid',
        Final: 'Final bid',
        text: 'The last bidder was motivated 10000 NEST',
    },
}
