const languageChinese = {
	message1: {
		Nomessage: '暂无消息',
		Oracle: '预言机',
		Quote: '报价',
		Income: '收益',
		address: 'Token 地址',
		price: '输入价格',
		USDT: 'USDT',
		Staking: '质押资产',
		Fee: '手续费',
		Estimated: '预估出矿',
		balanceETH: 'ETH 余额',
		balanceUSDT: '余额',
		amount: '最大值',
		quqteBtn: '报价挖矿',
		Verifying: '待验证报价',
		Quoteuser: '报价',
		progress: '验证进度',
		TAKER: '吃单',
		RETRIEVE: '取回',
		Penalty: '报价偏离惩罚',
		Penaltybottom: '与最新报价价格偏差 10%，当前报价至少需要质押 100 ETH 规模资产',
		Penaltybottom2: '与最新报价价格偏差 10%，当前报价至少需要质押 300 ETH 规模资产',
		CONFIRMbtn: '确定',
		Penaltybottoms: '与最新报价家偏差 10%，当前报价需要质押 30 倍规模资产',
		Annualized: '持有 NEST 年化收益率',
		average: '持有 NEST 7日平均年化收益率',
		Cumufative: '报价次数(24H)',
		Incomecontract: '系统收益合约地址',
		Incomecontract2: ' Token地址',
		NEST: ' token 地址',
		Depositincome: '存入 ',
		Depositincome2: ' 领取收益',
		total: ' 总流通量',
		SavedNEST: '已存入 ',
		earningspercentage: '我的收益占比',
		balanceNEST: ' 余额',
		Approvedamount: '授权数量',
		WITHDRAW: '取出',
		DEPOSITE: '存入',
		distribution: '距离收益发放还有',
		distribution2: '剩余领取时间',
		totals: 'ETH 总收益',
		Savings: '储蓄基金余额',
		My: '我的 ETH 收益',
		CLAIM: '领取收益',
		Quotation: '暂无报价',
		AllOracle: '所有预言机',
		Favorites: '我的收藏',
		fh_warn: '暂无可领取收益',
		day: '天',
		hours: '小时',
		sec: '分钟',
		connect: '连接钱包',
		pc_warn: '报价偏离惩罚!',
		null: '报价不能为空',
		sysj: "收益领取阶段未开启",
		crsj: "收益领取期不能存入",
		sq: "已授权",
		ysq: '授权',
		qp_ysq: '点击取消授权',
		qp_wsq: '点击授权'
	},
	message2: {
		Taker: 'ETH/DAI 报价吃单',
		Choose: '选择吃单方向和金额',
		Quoteprice: '价格',
		In: '获得',
		Pay: '支付',
		Fee: '手续费',
		quotation: '补充报价',
		text: '吃单需要发起一笔新的报价，报价质押资产是吃单资产规模的 2 倍',
		ETHbalance: 'ETH 余额',
		USDTbalance: 'USDT 余额',
		Approvedamount: '授权数量',
		USDTApprove: 'USDT 授权',
		CANCEL: '取消',
		CONFIRM: '确定',
		Customize: '自定义',
		MAX: '最大值',
		n_bz: ' 余额不足',
		sq_bz: '授权额度不足',
		saved_nest: '存入 ',
	},
	message3: {
		auction: '创建拍卖',
		Token: '预言机 Token 地址',
		pair: '报价交易对',
		output: '挖矿产出',
		authority: '初始权限拍卖',
		amount: '初始拍卖金额',
		duration: '拍卖持续时间',
		NEST: ' 余额',
		Approved: '授权数量',
		balance: 'DAI 余额',
		Oracle: 'ETH/DAI 预言机拍卖',
		address: 'DAI 地址',
		Lasted: '最新出价',
		bid: '我的出价',
		Final: '最终出价',
		text: '上个竞拍者可获得激励 10,000 NEST',
	},
}
